version: "3"

services:
    app:
        build: qac-app
        ports:
            - 5000:80

    api:
        build: qac-api
        ports:
            - 5001:80

    proxy:
        build: proxy
#        ports:
#            - 5000:80
